stages:
  - build
  - test
  - doc
  - trigger
    
build:linux:
  image: python:3.7-buster
  stage: build
  before_script:
    - pip install --upgrade -r requirements.txt
  script:
    - pip wheel .
  artifacts:
    paths:
      - zhinst_toolkit*.whl  

test:linux:
  image: python:3.7-buster
  stage: test
  before_script:
    - pip install --upgrade -r requirements.txt
    - pip install zhinst_toolkit-*.whl
  script:
    - pytest tests/

build:doc:
  image: docker-registry.zhinst.com/devops/dockerfiles/buildenv-doc:latest
  stage: doc
  before_script:
    - pip install --upgrade -r requirements.txt
    - pip install zhinst_toolkit-*.whl
    - apt-get -y update
    - apt-get -y install pandoc
  script:
    - cd docs
    - pip install -r requirements.txt
    - make html
  artifacts:
    paths:
      - docs/build/html
      
staging:
  variables:
    DS_PROJECT_NAME: $CI_PROJECT_NAME
    DS_PROJECT_ID: $CI_PROJECT_ID
    DS_PIPELINE_ID: $CI_PIPELINE_ID
  stage: trigger
  trigger:
    project: docs/staging
  rules:
    - if: '$CI_COMMIT_TAG'
